flaskr/flaskr/views/routes.py
from flask import Flask, request, session, g, redirect, url_for, abort, \
     render_template, flash, Blueprint

from flaskr.flaskr import db, getCategories
from flaskr import models
from flaskr import forms

flaskr_blueprint = Blueprint('flaskr', __name__, url_prefix='')
#Viewing Functions
#shows the entries in the database based on id number
#     -id number is based on time of entry(unless specified); newest at top
@flaskr_blueprint.route('/')
def show_entries():
    entries = models.Post.query.all()
    return render_template('show_entries.html', entries=entries)


#adds entries with POST requests and redirects back to show_entries main page otherwise fails with error
@flaskr_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    if not session.get('logged_in'):
        abort(401)
    form = forms.Add(request.form)
    form.category_id.choices = getCategories()
    error = 0
    if request.method == 'POST' and form.validate():
        db.session.add(models.Post(title=form.title.data,
                                   text=form.text.data,
                                   author=request.cookies.get('YourSessionCookie'),
                                   category_id=form.category_id.data))
        db.session.commit()
        flash('Added Succesfully')
        return redirect(url_for('flaskr.show_entries'))
    return render_template('add.html', error=error, form=form)


#removes entries with POST requests and redirects back to show_entries main page otherwise fails with error
@flaskr_blueprint.route('/remove', methods=['GET', 'POST'])
def remove():
    if not session.get('logged_in'):
        abort(401)
    form = forms.Remove(request.form)
    error = 0
    if request.method == 'POST' and form.validate():
        if models.Post.query.filter(models.Post.title == form.title.data).all():
            post = models.Post.query.filter_by(title=form.title.data).one()
            if post.author == request.cookies.get('YourSessionCookie') or \
                            request.cookies.get('YourSessionCookie') == 'admin':
                db.session.delete(post)
                db.session.commit()
                flash('Removed Succesfully')
                return redirect(url_for('flaskr.show_entries'))

            else:
                error = 'Must be admin or author to remove posts'
        else:
            error = 'Invalid Title'
    return render_template('remove.html', error=error, form=form)


# login and out functions
#login
@flaskr_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    error = 0
    form = forms.LoginForm(request.form)
    if request.method == 'POST' and form.validate():

        #check if user is in user db
        if models.User.query.filter(models.User.username == form.username.data).all():

            #check if user pw is correct
            if form.password.data == models.User.query.filter_by(username=form.username.data).one().pw:
                user = models.User.query.filter_by(username=form.username.data).one()
                session['logged_in'] = True
                flash('You are now logged in')
                response = redirect(url_for('flaskr.show_entries'))
                response.set_cookie('YourSessionCookie', user.username)
                return response

            else:
                error = 'Invalid Password'

        else:
            error = 'Invalid Username'

    return render_template('login.html', error=error, form=form)




#logout
@flaskr_blueprint.route('/logout')
def logout():
    session.pop('logged_in', None)
    flash('You were logged out')
    return redirect(url_for('flaskr.show_entries'))



#adds user with POST requests and redirects back to show_entries main page otherwise fails with error
@flaskr_blueprint.route('/adduser', methods=['GET', 'POST'])
def adduser():
    form = forms.Adduser(request.form)
    error = 0
    if request.method == 'POST':
        if form.validate():
            db.session.add(models.User(name=form.name.data, username=form.username.data, pw=form.pw.data))
            db.session.commit()
            flash('Added Succesfully')
            session['logged_in'] = True
            response = redirect(url_for('flaskr.show_entries'))
            user = models.User.query.filter_by(username=form.username.data).one()
            response.set_cookie('YourSessionCookie', user.username)
            return response
        else:
            error = 'All field lengths must be between 1 and 25 characters.'
    return render_template('adduser.html', error=error, form=form)


#adds user with POST requests and redirects back to show_entries main page otherwise fails with error
@flaskr_blueprint.route('/removeuser', methods=['GET', 'POST'])
def removeuser():
    form = forms.Removeuser(request.form)
    error = 0
    if request.method == 'POST':
        if form.validate():
            if models.User.query.filter(models.User.username == form.username.data).all():
                user = models.User.query.filter_by(username=form.username.data).one()
                if user.username == request.cookies.get('YourSessionCookie') or \
                                request.cookies.get('YourSessionCookie') == 'admin':
                    db.session.delete(user)
                    db.session.commit()
                    flash('Removed Succesfully')

                    if request.cookies.get('YourSessionCookie') != 'admin':
                        return redirect(url_for('logout'))
                    return redirect(url_for('flaskr.show_entries'))

                else:
                    error = 'Must be admin to remove other users'
            else:
                error = 'Invalid Username'
    return render_template('removeuser.html', error=error, form=form)


def shutdown_server():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()

@flaskr_blueprint.route('/shutdown', methods=['GET', 'POST'])
def shutdown():
    session.clear()
    shutdown_server()
    return 'Server shutting down...'

@flaskr_blueprint.route('/addcategory', methods=['GET', 'POST'])
def addcategory():
    if not session.get('logged_in'):
        abort(401)
    form = forms.AddCategory(request.form)
    if request.method == 'POST' and form.validate():
        db.session.add(models.Category(name=form.name.data))
        db.session.commit()
        flash('Added Succesfully')
        return redirect(url_for('flaskr.show_entries'))
    return render_template('addcategory.html', error=0, form=form)

flaskr/flaskr/templates/add.html
{% extends "layout.html" %}
{% block body %}
<div><a href="{{ url_for('flaskr.show_entries') }}">Home</a></div>
<h2>Add Entries</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form method=post>
    <dl>
      <dt><h2>{{ form.title.label }}</h2>
          <dd>{{ form.title(size=20) }}
      <dt><h3>{{ form.text.label }}</h3>
        <dd>{{ form.text(rows="5", cols="40") }}
       <dt>{{ form.category_id.label }}
        <dd>{{ form.category_id }}
    </dl>
    <p><input type=submit value=Add>
  </form>
{% endblock %}

flaskr/flaskr/templates/addcategory.html
{% extends "layout.html" %}
{% block body %}
<div><a href="{{ url_for('show_entries') }}">Home</a></div>
<h2>Add Category</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form method=post>
    <dl>
      <dt><h2>{{ form.name.label }}</h2>
          <dd>{{ form.name(size=20) }}
    </dl>
    <p><input type=submit value=Add>
  </form>
{% endblock %}

flaskr/flaskr/templates/adduser.html
{% extends "layout.html" %}
{% block body %}
  <h2>Create New User</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form method=post>
    <dl>
      <h2>{{ form.name.label }}</h2> {{ form.name(size=20) }}
      <h2>{{ form.username.label }}</h2> {{ form.username(size=20) }}
        <h2>{{ form.pw.label }}</h2> {{ form.pw(size=20) }}
    </dl>
    <p><input type=submit value=Create>
  </form>
{% endblock %}

flaskr/flaskr/templates/layout.html
<!doctype html>
<a href="{{  url_for('flaskr.show_entries') }}"><title>Flaskr</title></a>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
<div class=page>
  <h1>Flaskr</h1>
  <div class=metanav>
  {% if not session.logged_in %}
    <a href="{{ url_for('flaskr.login') }}">log in</a>        <a href="{{ url_for('flaskr.adduser') }}">Create User</a>
  {% else %}
    <a href="{{ url_for('flaskr.logout') }}">log out</a>
    <a href="{{ url_for('flaskr.removeuser') }}">Remove User</a>
      <a href="{{ url_for('flaskr.shutdown') }}">Shutdown</a>
  {% endif %}
  </div>
  <div class=metanav>
      {% if session.logged_in %}
        <a href="{{ url_for('flaskr.addcategory') }}">Add Category</a>
    <a href="{{ url_for('flaskr.remove') }}">Remove Post</a>
    {% endif %}
  </div>
  {% for message in get_flashed_messages() %}
    <div class=flash>{{ message }}</div>
  {% endfor %}
  {% block body %}{% endblock %}
</div>

flaskr/flaskr/templates/login.html
{% extends "layout.html" %}
{% block body %}
  <h2>Login</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form method=post>
    <dl>
      <h2>{{ form.username.label }}</h2> {{ form.username(size=20) }}
      <h2>{{ form.password.label }}</h2> {{ form.password(size=20) }}
    </dl>
    <p><input type=submit value=Login>
  </form>
{% endblock %}

flaskr/flaskr/templates/remove.html
{% extends "layout.html" %}
{% block body %}
<div><a href="{{ url_for('show_entries') }}">Home</a></div>
<h2>Remove Entries</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form method=post>
    <dl>
      <dt><h2>{{ form.title.label }}</h2>
      <dd>{{ form.title(size=20) }}
    </dl>
    <p><input type=submit value=Remove>
  </form>
{% endblock %}

flaskr/flaskr/templates/removeuser.html
{% extends "layout.html" %}
{% block body %}
  <h2>Remove User</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form method=post>
    <dl>
      <h2>{{ form.username.label }}</h2> {{ form.username(size=20) }}
    </dl>
    <p><input type=submit value=Remove>
  </form>
{% endblock %}

flaskr/flaskr/templates/show_entries.html
{% extends "layout.html" %}
{% block body %}
  {% if session.logged_in %}
      <a href="add">Add an entry.</a>
  {% endif %}
  <ul class=entries>
  {% for entry in entries %}
    <li><h2>{{ entry.title }}</h2><h3>{{ entry.text|safe }}</h3>
  {% else %}
    <li><em>Unbelievable.  No entries here so far</em>
  {% endfor %}
  </ul>
{% endblock %}